export enum Sistema {
  ROLLER = 'ROLLER',
  VERTICALES = 'VERTICALES',
  PERSIANA = 'PERSIANA',
  TELA = 'TELA',
  DUBAI = 'DUBAI',
  ORIENTAL = 'ORIENTAL',
  ROMANA = 'ROMANA',
  ZEBRA = 'ZEBRA',
  ADICIONAL = 'ADICIONAL',
  VACIO = 'VACIO'
}
